### PR TITLE
Now using Maven to download the Blazegraph jar.

### LINKED ISSUE #3: consider alternative to downloading bg jar
@kltm suggests checking in jar, but about mvn/ivy/sbt/gradle instead? http://mvnrepository.com/artifact/com.blazegraph/bigdata-core

### PR DESCRIPTION
**Pull request by balhoff**
Fixes #3.

### CODE REVIEW

**Comment by cmungall** [comment]
Look like you need to set bgVersion - how do we avoid setting the version twice?

**Comment by balhoff** [comment]
It is in the Makefile - it gets passed in the `$(BGJAR)` target. I didn't realize Travis was going to run maven.

**Comment by cmungall** [comment]
looks like the travis has never been functional, go ahead and merge and we can fix that later

**Comment by balhoff** [comment]
Okay, can you give me permissions here?

**Comment by cmungall** [comment]
OK, you should have it

**Pull request merged**
